#!/usr/bin/env python3
"""Generate the tonemapper's blue-noise dither tables.

Writes `servers/rendering/renderer_rd/effects/blue_noise_64.h`: three independent 64x64
void-and-cluster rank tables (Ulichney 1993), one per colour channel, quantised to 8 bits so
every value appears exactly 16 times. The tonemap shaders fold each into a triangular dither.

Deterministic: fixed seeds, no threads, no platform-dependent maths beyond numpy's FFT-free
float64 path. Re-run only to change the recipe, and commit the header with the script.

    uv run --with numpy hogdot/gen_blue_noise.py
"""

from __future__ import annotations

import pathlib

import numpy as np

SIZE = 64
SIGMA = 1.9  # Ulichney's filter width; wider makes the spectrum bluer but the pattern more regular.
SEEDS = (0x1D17, 0x2E28, 0x3F39)
OUT = pathlib.Path(__file__).resolve().parent.parent / "servers/rendering/renderer_rd/effects/blue_noise_64.h"

HEADER = """\
/**************************************************************************/
/*  blue_noise_64.h                                                       */
/**************************************************************************/
/*                         This file is part of:                          */
/*                             GODOT ENGINE                               */
/*                        https://godotengine.org                         */
/**************************************************************************/
/* Copyright (c) 2014-present Godot Engine contributors (see AUTHORS.md). */
/* Copyright (c) 2007-2014 Juan Linietsky, Ariel Manzur.                  */
/*                                                                        */
/* Permission is hereby granted, free of charge, to any person obtaining  */
/* a copy of this software and associated documentation files (the        */
/* "Software"), to deal in the Software without restriction, including    */
/* without limitation the rights to use, copy, modify, merge, publish,    */
/* distribute, sublicense, and/or sell copies of the Software, and to     */
/* permit persons to whom the Software is furnished to do so, subject to  */
/* the following conditions:                                              */
/*                                                                        */
/* The above copyright notice and this permission notice shall be         */
/* included in all copies or substantial portions of the Software.        */
/*                                                                        */
/* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,        */
/* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF     */
/* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. */
/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY   */
/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,   */
/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE      */
/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                 */
/**************************************************************************/

#pragma once

#include <cstdint>

// Three 64x64 blue-noise rank tables, one per colour channel, quantised to 8 bits so that every
// value appears exactly 16 times (a uniform distribution the tonemapper folds into a triangle).
// Generated by hogdot/gen_blue_noise.py (void-and-cluster, sigma 1.9, toroidal); never edit by
// hand, re-run the script. The ToneMapper tiles them into its noise texture at creation.
"""


def wrapped_gaussian(size: int, sigma: float) -> np.ndarray:
    axis = np.arange(size)
    delta = np.minimum(axis, size - axis).astype(np.float64)
    one_d = np.exp(-(delta * delta) / (2.0 * sigma * sigma))
    return np.outer(one_d, one_d)


def void_and_cluster(size: int, sigma: float, seed: int) -> np.ndarray:
    """Ulichney's method: returns a rank per texel, 0..size*size-1, each exactly once."""
    rng = np.random.default_rng(seed)
    count = size * size
    kernel = wrapped_gaussian(size, sigma)

    def energy_of(pattern: np.ndarray) -> np.ndarray:
        # Toroidal convolution through FFT: the pattern is small, so this is exact and fast.
        return np.real(np.fft.ifft2(np.fft.fft2(pattern) * np.fft.fft2(kernel)))

    # Initial binary pattern: about a tenth of the texels, then swapped until the tightest
    # cluster and the largest void coincide.
    pattern = np.zeros((size, size), dtype=np.float64)
    ones = rng.choice(count, size=count // 10, replace=False)
    pattern.flat[ones] = 1.0
    while True:
        energy = energy_of(pattern)
        cluster = int(np.argmax(np.where(pattern > 0.5, energy, -np.inf)))
        pattern.flat[cluster] = 0.0
        energy = energy_of(pattern)
        void = int(np.argmin(np.where(pattern < 0.5, energy, np.inf)))
        pattern.flat[void] = 1.0
        if void == cluster:
            break

    rank = np.full(count, -1, dtype=np.int64)
    initial = pattern.copy()

    # Phase 1: peel the initial ones off, tightest cluster first, ranking downwards.
    working = initial.copy()
    remaining = int(working.sum())
    while remaining > 0:
        energy = energy_of(working)
        cluster = int(np.argmax(np.where(working > 0.5, energy, -np.inf)))
        working.flat[cluster] = 0.0
        remaining -= 1
        rank[cluster] = remaining

    # Phase 2: fill the largest void until half the texels are on.
    working = initial.copy()
    filled = int(working.sum())
    while filled < count // 2:
        energy = energy_of(working)
        void = int(np.argmin(np.where(working < 0.5, energy, np.inf)))
        working.flat[void] = 1.0
        rank[void] = filled
        filled += 1

    # Phase 3: on the inverted pattern, the tightest cluster of zeros is the next largest void.
    while filled < count:
        energy = energy_of(1.0 - working)
        cluster = int(np.argmax(np.where(working < 0.5, energy, -np.inf)))
        working.flat[cluster] = 1.0
        rank[cluster] = filled
        filled += 1

    assert sorted(rank.tolist()) == list(range(count))
    return rank.reshape(size, size)


def spectrum_report(rank: np.ndarray) -> str:
    """The share of spectral energy below a quarter of Nyquist; white noise scores about 0.04."""
    centered = rank.astype(np.float64) - rank.mean()
    power = np.abs(np.fft.fft2(centered)) ** 2
    power[0, 0] = 0.0
    freq = np.fft.fftfreq(rank.shape[0])
    radius = np.sqrt(freq[:, None] ** 2 + freq[None, :] ** 2)
    low = power[radius < 0.125].sum() / power.sum()
    return f"low-frequency energy share {low:.4f}"


def main() -> None:
    tables = []
    for seed in SEEDS:
        rank = void_and_cluster(SIZE, SIGMA, seed)
        print(f"seed {seed:#06x}: {spectrum_report(rank)}")
        tables.append((rank * 256) // (SIZE * SIZE))
    lines = [HEADER, "// clang-format off", f"static const uint8_t BLUE_NOISE_64[3][{SIZE * SIZE}] = {{"]
    for table in tables:
        lines.append("\t{")
        flat = table.flatten().tolist()
        for row in range(0, len(flat), 32):
            lines.append("\t\t" + ", ".join(str(int(v)) for v in flat[row : row + 32]) + ",")
        lines.append("\t},")
    lines.append("};")
    lines.append("// clang-format on")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
