name: Upload Godot artifact
description: Upload the Godot artifact.

inputs:
  name:
    description: The artifact name.
    default: ${{ github.job }}
  path:
    description: The path to upload.
    required: true
    default: bin/*

runs:
  using: composite
  steps:
    - name: Upload Godot Artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
        # Default is 90 days.
        retention-days: 60
